In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [3]:
y = np.array( [ [1,2,3], [4,5,6], [7,8,9] ] )
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# two
print(y[0,0])
print(y[0,1])
print(y[1,-1])

1
2
6


In [5]:
y.ndim

2

In [6]:
y.shape

(3, 3)

In [7]:
z = np.zeros(4)
z

array([0., 0., 0., 0.])

In [8]:
ones = np.ones(4)
ones

array([1., 1., 1., 1.])

In [9]:
ar = np.arange(5)
ar

array([0, 1, 2, 3, 4])

In [10]:
t = np.array([[[1,2],[3,4]],[[5,6], [7,8]]])
print(t, '\n')
print(t.shape, '\n')
print(t.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 

(2, 2, 2) 

3


In [11]:
x = np.arange(5)
print(x)

[0 1 2 3 4]


In [12]:
empty = np.array([])

In [13]:
print(empty.shape)

(0,)
