In [1]:
import numpy as np

In [3]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [22]:
y = np.array( [ [1,2,3], [4,5,6], [7,8,9] ] )
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
# two
print(y[0,0])
print(y[0,1])
print(y[1,-1])

1
2
6


In [26]:
y.ndim

2

In [27]:
y.shape

(3, 3)

In [28]:
z = np.zeros(4)
z

array([0., 0., 0., 0.])

In [30]:
ones = np.ones(4)
ones

array([1., 1., 1., 1.])

In [33]:
ar = np.arange(5)
ar

array([0, 1, 2, 3, 4])

In [39]:
t = np.array([[[1,2],[3,4]],[[5,6], [7,8]]])
print(t, '\n')
print(t.shape, '\n')
print(t.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 

(2, 2, 2) 

3
