In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
cols = ['MedInc', 'HouseAge', 'Population', 'MedHouseVal']

In [3]:
for i,x in enumerate(cols):
    print(f'index {i}: {x}')

index 0: MedInc
index 1: HouseAge
index 2: Population
index 3: MedHouseVal


In [13]:
A = np.array([1,2,3,4,5,6])
print(A)

[1 2 3 4 5 6]


In [14]:
print(A.shape)
print(A.ndim)

(6,)
1


In [28]:
B = np.array([ [ [1,2,3],['a','b','c'] ], [ [4,5,6],['a', 'b', 'c'] ] , [ [7,8,9], ['a', 'b', 'c'] ] ])
print(B)

[[['1' '2' '3']
  ['a' 'b' 'c']]

 [['4' '5' '6']
  ['a' 'b' 'c']]

 [['7' '8' '9']
  ['a' 'b' 'c']]]


In [31]:
print(B.shape)
print(B.ndim)

(3, 2, 3)
3


In [1]:
from sklearn import datasets
dir(datasets)

['__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_arff_parser',
 '_base',
 '_california_housing',
 '_covtype',
 '_kddcup99',
 '_lfw',
 '_olivetti_faces',
 '_openml',
 '_rcv1',
 '_samples_generator',
 '_species_distributions',
 '_svmlight_format_fast',
 '_svmlight_format_io',
 '_twenty_newsgroups',
 'clear_data_home',
 'dump_svmlight_file',
 'fetch_20newsgroups',
 'fetch_20newsgroups_vectorized',
 'fetch_california_housing',
 'fetch_covtype',
 'fetch_kddcup99',
 'fetch_lfw_pairs',
 'fetch_lfw_people',
 'fetch_olivetti_faces',
 'fetch_openml',
 'fetch_rcv1',
 'fetch_species_distributions',
 'get_data_home',
 'load_breast_cancer',
 'load_diabetes',
 'load_digits',
 'load_files',
 'load_iris',
 'load_linnerud',
 'load_sample_image',
 'load_sample_images',
 'load_svmlight_file',
 'load_svmlight_files',
 'load_wine',
 'make_biclusters',
 'make_blobs',
 'make_checkerboard',
 'make_circl

In [16]:
from sklearn.datasets import fetch_california_housing
df_housing = fetch_california_housing()
print(df_housing.data.shape, df_housing.target.shape)
#display all features(columns)
print(df_housing.feature_names[:])


(20640, 8) (20640,)
['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']


In [5]:
X = df_housing.data
X


array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]])

In [6]:
y = df_housing.target 
y

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [14]:
df = pd.DataFrame(data = fetch_california_housing.data, columns = fetch_california_housing.feature_names)

AttributeError: module 'pandas' has no attribute 'X'